.github/workflows/utility-libraries.yml, utility-libraries/README.md, utility-libraries/custom_lib_example/Dockerfile, utility-libraries/custom_lib_example/README.md, utility-libraries/custom_lib_example/app/LICENSE, utility-libraries/custom_lib_example/app/Makefile, utility-libraries/custom_lib_example/app/custom_build/Makefile, utility-libraries/custom_lib_example/app/custom_build/hello_world.c, utility-libraries/custom_lib_example/app/custom_build/hello_world.h, utility-libraries/custom_lib_example/app/customlib_example.c, utility-libraries/custom_lib_example/app/manifest.json
Change-Id: Icfeeeff4ecf757fce02961435fe43e84cacbd182
=> Added custom library example in utility libraries

axoverlay/README.md, container-example/README.md, web-server/README.md
* Update mentioning of ACAP 4
* axoverlay - list order
=> README updates from sync

object-detection/README.md, tensorflow-to-larod-artpec8/README.md, tensorflow-to-larod/README.md
For easier maintenance.
Reference: ECODEVT-116
=> Replace API links from 4.* to src

container-example/README.md
Add additional install command for container-example
Fixes AxisCommunications/acap-native-sdk-examples#48
Reference: AFT-280
=> Updated README.md

LICENSE, axevent/send_event/app/LICENSE, axevent/subscribe_to_event/app/LICENSE, axevent/subscribe_to_events/app/LICENSE, axoverlay/app/LICENSE, container-example/LICENSE, hello-world/app/LICENSE, larod/app/LICENSE, licensekey/app/LICENSE, object-detection/app/LICENSE, reproducible-package/app/LICENSE, shell-script-example/app/LICENSE, tensorflow-to-larod-artpec8/env/app/LICENSE, tensorflow-to-larod/env/app/LICENSE, using-opencv/app/LICENSE, utility-libraries/custom_lib_example/app/LICENSE, utility-libraries/openssl_curl_example/app/LICENSE, vdo-larod-preprocessing/app/LICENSE, vdo-larod/app/LICENSE, vdo-opencl-filtering/app/LICENSE, vdostream/app/LICENSE, web-server/app/LICENSE
In license texts the name of the company should be denoted as Axis Communications AB.
=> docs(license): update company name

using-opencv/app/imgprovider.cpp
This makes the example work for CV25
=> Adding a filter for VDO_FORMAT_YUV to get correct resolutions

tensorflow-to-larod-cv25/README.md
=> Ambarella tools registering

container-example/containerExample
- Use INT and TERM instead of their numbers directly
- Add longer sleep for the dummy loop since the interrupt will be trapped when it comes anyway, so no need to loop every second. To still have the infinity loop, sleep one week in every iteration.
- Remove superfluous quotes
=> containerExample: Use signal names instead of numbers

.eslintrc.yml, .github/workflows/linter.yml, .vscode/extensions.json, LINT.md
* Use the default super-linter configuration
* Add recommended VS Code extenstion
=> lint: Add JSON linter

LICENSE
Reference: https://www.apache.org/licenses/LICENSE-2.0.html#apply
=> Update LICENSE copyright format

object-detection-cv25/README.md
- Adding information about padding
- CV25 update padding information
=> Add object-detection-cv25 padding info

object-detection/README.md
Co-authored-by: Angelo Delli Santi <dellisanti.angelo@gmail.com>
=> fix object-detection README

.github/workflows/axstorage.yml, README.md, axstorage/Dockerfile, axstorage/README.md, axstorage/app/LICENSE, axstorage/app/Makefile, axstorage/app/axstorage.c, axstorage/app/manifest.json
Co-authored-by: Mar Balibrea Rull <marb@axis.com>
Co-authored-by: Mattias Kindborg <mattiask@axis.com>
Co-authored-by: Angelo DelliSanti <angelod@axis.com>
=> Add axstorage example

axevent/send_event/app/manifest.json, axevent/subscribe_to_event/app/manifest.json, axevent/subscribe_to_events/app/manifest.json, axoverlay/app/manifest.json, axserialport/app/manifest.json, axstorage/app/manifest.json, container-example/manifest.json, hello-world/app/manifest.json, licensekey/app/manifest.json, object-detection-cv25/app/manifest.json.cv25, object-detection/app/manifest.json.artpec8, object-detection/app/manifest.json.cpu, object-detection/app/manifest.json.edgetpu, reproducible-package/app/manifest.json, shell-script-example/app/manifest.json, using-opencv/app/manifest.json, utility-libraries/custom_lib_example/app/manifest.json, utility-libraries/openssl_curl_example/app/manifest.json, vdo-larod/app/manifest.json.artpec8, vdo-larod/app/manifest.json.cpu, vdo-larod/app/manifest.json.cv25, vdo-larod/app/manifest.json.edgetpu, vdo-opencl-filtering/app/manifest.json, vdostream/app/manifest.json, web-server-using-fastcgi/app/manifest.json, web-server/app/manifest.json
=> Automatic update of versions

axoverlay/app/Makefile, axoverlay/app/manifest.json
Update axoverlay example to use dynamic user.
=> axoverlay: Update to dynamic user

.github/workflows/web-server.yml, web-server/Dockerfile, web-server/README.md, web-server/app/manifest.json, web-server/app/postinstall.sh, web-server/app/preuninstall.sh, web-server/app/reverseproxy.conf
Update web server to work without root
=> Web server rootless update

.github/workflows/axparameter.yml, README.md, axparameter/Dockerfile, axparameter/README.md, axparameter/app/LICENSE, axparameter/app/Makefile, axparameter/app/axparameter.c, axparameter/app/manifest.json
Co-authored-by: Mattias Axelsson <mattiaax@axis.com>
Co-authored-by: Angelo DelliSanti <angelod@axis.com>
Co-authored-by: Stiv Abdullwahed <stiva@axis.com>
=> axparameter: Add example

.github/workflows/metadata-broker.yml, README.md, metadata-broker/README.md, metadata-broker/consume-analytics-scene-description/Dockerfile, metadata-broker/consume-analytics-scene-description/README.md, metadata-broker/consume-analytics-scene-description/app/LICENSE, metadata-broker/consume-analytics-scene-description/app/Makefile, metadata-broker/consume-analytics-scene-description/app/consume_analytics_metadata.c, metadata-broker/consume-analytics-scene-description/app/manifest.json
Add first example consume-analytics-scene-description of Metadata
Broker API.
=> Add metadata-broker example

.github/workflows/container-example.yml, container-example/.gitignore, container-example/Dockerfile, container-example/README.md, container-example/config/env.aarch64, container-example/config/env.armv7hf, container-example/containerExample, container-example/docker-compose.yml, container-example/manifest.json, container-example/preuninstall.sh
Co-authored-by: Patrik Åkesson <66364872+pataxis@users.noreply.github.com>
=> Updated container example for dynamic user

axstorage/app/axstorage.c
=> axstorage: Align log facility argument to LOG_USER

.github/workflows/vdo-opencl-filtering.yml
=> workflows: Remove unused chip in build instructions

axevent/send_event/README.md, axevent/subscribe_to_event/README.md, axevent/subscribe_to_events/README.md, axoverlay/README.md, curl-openssl/README.md, hello-world/README.md, metadata-broker/consume-analytics-scene-description/README.md, shell-script-example/README.md, utility-libraries/custom_lib_example/README.md, utility-libraries/openssl_curl_example/README.md, vdo-larod/README.md, vdostream/README.md
=> Remove instructions of accessing log via SSH

.github/lint-device-urls.sh, .github/workflows/linter-documentation-links.yml, axevent/README.md, axevent/send_event/README.md, axevent/subscribe_to_event/README.md, axevent/subscribe_to_events/README.md, axoverlay/README.md, axparameter/README.md, axserialport/README.md, axstorage/README.md, container-example/README.md, curl-openssl/README.md, hello-world/README.md, licensekey/README.md, metadata-broker/consume-analytics-scene-description/README.md, shell-script-example/README.md, utility-libraries/custom_lib_example/README.md, vapix/README.md, vdo-larod/README.md, vdo-opencl-filtering/README.md, vdostream/README.md, web-server-using-fastcgi/README.md, web-server/README.md
* Lint: Add linter for device URLs
* Lint: Add check of device ip naming
* Align to AXIS_DEVICE_IP
* Update README links to follow device URL format
=> Align device ip in docs

DEV.md, README.md, curl-openssl/README.md, utility-libraries/openssl_curl_example/README.md, vdo-opencl-filtering/README.md
* DEV.md: Add page with common developer topics
* Update examples to not use root user for ssh
=> Update SSH cmds to non root

container-example/docker-compose.yml
This reverts commit 92128fa21f730755191ffea506169c28e6421c09.
=> Revert "chore(deps): update alpine docker tag to v3.20.0"

DEV.md
=> DEV.md: Add sections for accessing logs and reports

axparameter/README.md
=> axparameter: Fix README typos

.github/lint-device-urls.sh, axevent/send_event/README.md, axparameter/README.md
=> Lint: Align the <AXIS_DEVICE_IP>/index.html# URLs

web-server/app/LICENSE
=> web-server: Add Monkey license to app/LICENSE

.github/workflows/remote-debug-example.yml, .vscode/extensions.json, DEV.md, README.md, remote-debug-example/.gitignore, remote-debug-example/Dockerfile, remote-debug-example/README.md, remote-debug-example/app/.devcontainer/aarch64-container/devcontainer.json, remote-debug-example/app/.devcontainer/armv7hf-container/devcontainer.json, remote-debug-example/app/.vscode/launch.json, remote-debug-example/app/LICENSE, remote-debug-example/app/Makefile, remote-debug-example/app/manifest.json, remote-debug-example/app/remote_debug.c
Co-authored-by: Patrik Åkesson <66364872+pataxis@users.noreply.github.com>
Co-authored-by: Stiv Abdullwahed <stiva@axis.com>
=> Add remote-debug-example

web-server-using-fastcgi/Dockerfile, web-server-using-fastcgi/app/LICENSE
* Add uriparser license
* Step uriparser version to 0.9.8
=> web-server-using-fastcgi: Update uriparser

.editorconfig, .vscode/hadolint
=> editorconfig: Update to syntax picking all shell scripts

object-detection-cv25/Dockerfile, object-detection-cv25/app/LICENSE, object-detection/Dockerfile, object-detection/app/LICENSE
Add missing libjpeg-turbo license.
=> object-detection*: Step libjpeg-turbo to 3.0.3

.github/custom-linters/lint-acap-version-urls.sh, .github/custom-linters/lint-device-urls.sh, .github/custom-linters/lint-example-structure.sh, .github/run-custom-linters, .github/utils/util-functions.sh, .github/workflows/linter-documentation-links.yml, .github/workflows/linter-example-checks.yml, .vscode/tasks.json, LINT.md, run-linters
* Make all custom linters callable locally and in CI
* Add script to start all linters locally
=> Lint: Refactor to run all linters with one command

using-opencv/Dockerfile, using-opencv/app/LICENSE
* Update opencv to version 4.10.0
* Update LICENSE file
=> Update opencv to version 4.10.0

.github/custom-linters/lint-device-urls.sh, .gitignore
* Ignore files from eap-install.sh
* Ignore the generated *_LICENSE.txt file
=> gitignore: Ignore files from interactive development

README.md
Co-authored-by: Patrik Åkesson <66364872+pataxis@users.noreply.github.com>
=> Update ACAP version to 12

curl-openssl/Dockerfile, remote-debug-example/Dockerfile, tensorflow-to-larod-artpec8/Dockerfile, utility-libraries/openssl_curl_example/Dockerfile, vapix/Dockerfile
- Remove multistage labels when there is no multiple stages
- Use keyword `AS` instead of `as` to get rid of docker build warning
=> Dockerfile multistage build housekeeping

.github/custom-linters/lint-acap-documentation-urls.sh, bounding-box/README.md, object-detection-cv25/README.md
- Add linter to check that relative paths are used
- Add linter to check for internal Axis repos
- Update ACAP documentation links for .md check
- Add check of Docker private repo URLs
=> lint: Multiple lint additions

.github/workflows/remote-debug-example.yml
This reverts commit d0929b5efe836b9de36e4cbc16203b479e885440.
=> Revert "Add nightly test for remote-debug-example"
