AxisCommunications/acap-native-sdk-examples

- object-detection/app/imgprovider.c
- tensorflow-to-larod-artpec8/env/app/imgprovider.c
- tensorflow-to-larod/env/app/imgprovider.c
- using-opencv/app/imgprovider.cpp
- vdo-larod-preprocessing/app/imgprovider.c
- vdo-larod/app/imgprovider.c
Need to release the ref from vdo_stream_get_buffer for the other buffer.
It's no longer recommended to use VDO_BUFFER_STRATEGY_EXPLICIT, instead
the default strategy INFINITE is preferred if possible. This is not
fixed in this commit.
Reference: AFT-273
> Update examples using VDO to make correct unref

- tensorflow-to-larod-artpec8/Dockerfile
- tensorflow-to-larod/Dockerfile
As of 27th of April, CUDA Linux added rotating keys to their libraries. This fix removes the GPG errors.
> cuda rotating keys fixed

- web-server/monkey.patch
There was a change in gcc 10 that doesn't allow multiple definitions of variables in different files.
Also, added another change (RLIMIT_NOFILE) to synch with acap-computer-vision-sdk-example.
- Fixes #(issue)
> Added ccflag to allow multiple definitions and synched native-sdk and cv-sdk

- utility-libraries/openssl_curl_example/Dockerfile
The pkgconfig folder was misspelled which means that the crypto and ssl package config files were left in the SDK root while the actual header files and library files were removed.
> Fix bug with isolation of openssl lib

- web-server/README.md
The original text 'Some C API examples are included in the app folder' is misleading and is implying to the reader to look/search for examples directly under axis repo 'web-server/app' directory itself and complain as examples missing. But in reality, those examples are available (as part of build procedure coded in Dockerfile) inside the container and hence suggested text is trying to address that concern.
Closes AxisCommunications/acap-native-sdk-examples#87
> Improved text to reduce interpretation ambiguity

- licensekey/README.md
- vdo-opencl-filtering/README.md
Wrong ACAP SDK documentation version referenced
* Change to general developer community link
* Use counter-part for ACAP Portal and OpenCL
> Update incorrect SDK documentation links

- utility-libraries/openssl_curl_example/Dockerfile
- utility-libraries/openssl_curl_example/README.md
The build error in openssl_curl_example that started in the 1.5 release came from that libcurl entered the ACAP Native SDK. The libcurl in the SDK took precedence over the custom built libcurl when linking the example binary. The libcurl from the SDK caused the build error due to a missing dependency libssh2 that got removed in the SDK build by a globbing rule mainly meant to remove libssl.
A simple removal of the libcurl files in the SDK path before starting the example build solves the issue and works with 1.5 release.
The curl build procedure using automake checks the environment and automatically depends on some libs that it can find in the SDK sysroot, like zlib and zstd used for compression of transferred data over HTTP. The libcurl build dependencies have also been skipped via …
> openssl_curl_example: Fix build error since 1.5 release

- container-example/containerExample
In container-example/containerExample script, pass --env-file "./env.config" parameter to the docker compose down command. Without this, the compose down command misses the ALPINE_IMAGE variable definition and fails, leaving the container up and running. 
Patch tested on a Q1656 Box device, firmware 11.4.63, with "Docker Compose" ACAP v1.3.0.
> container-example: pass --env-file parameter to docker compose down

- axoverlay/app/axoverlay.c
- axoverlay/app/manifest.json
It is good practice to use `const` for variables that are not to be changed.
> axoverlay: Use const where possible

- object-detection-cv25/README.md
- object-detection-cv25/app/manifest.json.cv25
- object-detection-cv25/app/object_detection.c
- object-detection/app/object_detection.c
Bug in object-detection* examples.
Fixes #138
> Fix bug that creates an empty output image

- web-server-using-fastcgi/app/fastcgi_example.c
If there are no query parameters specified, the application segfaulted since it did continue to try using the uri query list even if parsing them failed. This commit causes it to print the "Failed to parse .." text and then continue, waiting for the next request.
Correct error handling.
> Fix segfault in fastcgi app

- .github/workflows/linter.yml
- LINT.md
The linter has been blue badged.
> lint: Update to super-linter/super-linter

- object-detection/app/object_detection.c
When assigning pointers to `labelArray`, if the file had a final, empty newline, the last element of `labelArray` would try to be assigned to a pointer to `labelsData + labelsFileSize + 1`, which can cause a warning that can disrupt inference:
```
malloc(): invalid size (unsorted)
```
I also removed the replacement of the final `'\n'` with `'\0'` because it is always done in the loop.
> Fix overflow issue

- shell-script-example/README.md
Remove erroneous '.c' extension from shell_script_example in the first file listing.
Please include a summary of the change, a relevant motivation and context.
- Fixes #(issue)
> Fix typo in README.md

- vapix/README.md
> vapix: Fix erroneuos link in README

- .github/renovate.json
The version handling would need to be handled in a different way for
renovate to work for the container-example, which right now only update
one file and by that breaks the example.
> renovate: Skip updates of container-example

- .github/lint-device-urls.sh
> lint: Skip .git and other unrelated repos for device URL check

- DEV.md
- axevent/send_event/README.md
- axevent/subscribe_to_event/README.md
- axevent/subscribe_to_events/README.md
- axoverlay/README.md
- axparameter/README.md
- axserialport/README.md
- axstorage/README.md
- bounding-box/README.md
- container-example/README.md
- curl-openssl/README.md
- hello-world/README.md
- licensekey/README.md
- message-broker/consume-scene-metadata/README.md
- object-detection-cv25/README.md
- object-detection/README.md
- reproducible-package/README.md
- shell-script-example/README.md
- using-opencv/README.md
- utility-libraries/custom_lib_example/README.md
- utility-libraries/openssl_curl_example/README.md
- vapix/README.md
- vdo-larod/README.md
- vdo-opencl-filtering/README.md
- vdostream/README.md
- web-server-using-fastcgi/README.md
Co-authored-by: Patrik Åkesson <66364872+pataxis@users.noreply.github.com>
> DEV: Add proxy section

- .github/custom-linters/lint-acap-documentation-urls.sh
- .github/custom-linters/lint-device-urls.sh
- .github/custom-linters/lint-example-structure.sh
- .github/custom-linters/lint-super-linter-version.sh
- .github/renovate.json
- .github/run-custom-linters
- .github/workflows/linter-super-linter-version.yml
- LINT.md
- run-linters
- Use absolute path to git root to make it future-proof
- Remove renovate config to step super linter not working
- Align super-linter versions to workflow
- Add linter to check alignment of super-linter version
> Lint: Check alignment of super-linter version, Remove renovate config, remove abs path 

- object-detection-cv25/README.md
This reverts the link target to what it was before it was last changed in 6aa62c57b650ab2d76af35c007933a54e9c6f70b. The link target introduced by that commit, does not and has never existed in the repository and, since the context of the link did not change, I assume it should still point to the same example as it used to. But this is not correct:
> It shouldn't link to tesnorflow-to-larod-cv25 either since that is a model training example, not an ACAP application.
> fix(object-detection-cv25): Fix broken link in README
